/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: [
        "./src/**/*.{js,jsx,ts,tsx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
                display: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
                mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
            },
            colors: {
                brand: {
                    50:  '#f0fdf4',
                    100: '#dcfce7',
                    200: '#bbf7d0',
                    300: '#86efac',
                    400: '#4ade80',
                    500: '#22c55e',
                    600: '#16a34a',
                    700: '#15803d',
                    800: '#166534',
                    900: '#14532d',
                },
                accent: {
                    50:  '#fff7ed',
                    100: '#ffedd5',
                    200: '#fed7aa',
                    300: '#fdba74',
                    400: '#fb923c',
                    500: '#f97316',
                    600: '#ea580c',
                    700: '#c2410c',
                    800: '#9a3412',
                    900: '#7c2d12',
                },
                surface: {
                    0:   '#ffffff',
                    50:  '#fafaf9',
                    100: '#f5f5f4',
                    200: '#e7e5e4',
                    300: '#d6d3d1',
                    400: '#a8a29e',
                    500: '#78716c',
                    600: '#57534e',
                    700: '#44403c',
                    800: '#292524',
                    900: '#1c1917',
                    950: '#0c0a09',
                }
            },
            boxShadow: {
                'xs':         '0 1px 2px rgba(0,0,0,0.04)',
                'soft':       '0 2px 8px -2px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.04)',
                'card':       '0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.02)',
                'card-hover': '0 20px 60px -15px rgba(0,0,0,0.1), 0 8px 20px rgba(0,0,0,0.04)',
                'elevated':   '0 12px 40px -8px rgba(0,0,0,0.12)',
                'card-dark':       '0 1px 3px rgba(0,0,0,0.4)',
                'card-dark-hover': '0 20px 60px -15px rgba(0,0,0,0.5)',
                'glow':        '0 0 40px rgba(34,197,94,0.12)',
                'glow-accent': '0 0 40px rgba(249,115,22,0.12)',
                'inner-glow':  'inset 0 1px 0 rgba(255,255,255,0.06)',
                'ring':        '0 0 0 1px rgba(0,0,0,0.05)',
            },
            backgroundImage: {
                'gradient-brand':        'linear-gradient(135deg, #16a34a, #22c55e)',
                'gradient-brand-subtle': 'linear-gradient(160deg, #fafaf9, #f0fdf4, #fafaf9)',
                'gradient-dark-subtle':  'linear-gradient(160deg, #1c1917, #14532d08, #1c1917)',
                'gradient-warm':         'linear-gradient(135deg, #f5f5f4, #fff7ed)',
                'gradient-dark-warm':    'linear-gradient(135deg, #1c1917, #292524)',
                'mesh-light': 'radial-gradient(ellipse 80% 60% at 30% 0%, rgba(34,197,94,0.06) 0%, transparent 60%), radial-gradient(ellipse 60% 50% at 80% 100%, rgba(249,115,22,0.04) 0%, transparent 60%)',
                'mesh-dark':  'radial-gradient(ellipse 80% 60% at 30% 0%, rgba(34,197,94,0.08) 0%, transparent 60%), radial-gradient(ellipse 60% 50% at 80% 100%, rgba(249,115,22,0.05) 0%, transparent 60%)',
                'dots':       'radial-gradient(circle, rgba(0,0,0,0.06) 1px, transparent 1px)',
                'dots-dark':  'radial-gradient(circle, rgba(255,255,255,0.04) 1px, transparent 1px)',
            },
            backgroundSize: {
                'dots': '24px 24px',
            },
            borderRadius: {
                '4xl': '2rem',
                '5xl': '2.5rem',
            },
            letterSpacing: {
                'display': '-0.025em',
                'tight-2': '-0.02em',
            },
            animation: {
                'fade-in':     'fadeIn 0.6s cubic-bezier(0.16,1,0.3,1)',
                'slide-up':    'slideUp 0.5s cubic-bezier(0.16,1,0.3,1)',
                'slide-down':  'slideDown 0.5s cubic-bezier(0.16,1,0.3,1)',
                'scale-in':    'scaleIn 0.4s cubic-bezier(0.16,1,0.3,1)',
                'float':       'float 6s ease-in-out infinite',
                'float-slow':  'float 8s ease-in-out infinite',
                'pulse-soft':  'pulseSoft 3s ease-in-out infinite',
                'shimmer':     'shimmer 2.5s linear infinite',
                'gradient':    'gradientShift 8s ease infinite',
                'reveal':      'reveal 0.8s cubic-bezier(0.16,1,0.3,1)',
                'grain':       'grain 0.5s steps(1) infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%':   { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%':   { opacity: '0', transform: 'translateY(20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                slideDown: {
                    '0%':   { opacity: '0', transform: 'translateY(-20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                scaleIn: {
                    '0%':   { opacity: '0', transform: 'scale(0.95)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                float: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%':      { transform: 'translateY(-12px)' },
                },
                pulseSoft: {
                    '0%, 100%': { opacity: '1' },
                    '50%':      { opacity: '0.6' },
                },
                shimmer: {
                    '0%':   { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
                gradientShift: {
                    '0%, 100%': { backgroundPosition: '0% 50%' },
                    '50%':      { backgroundPosition: '100% 50%' },
                },
                reveal: {
                    '0%':   { opacity: '0', transform: 'translateY(30px) scale(0.98)' },
                    '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
                },
                grain: {
                    '0%, 100%': { transform: 'translate(0, 0)' },
                    '10%':      { transform: 'translate(-5%, -10%)' },
                    '20%':      { transform: 'translate(-15%, 5%)' },
                    '30%':      { transform: 'translate(7%, -25%)' },
                    '40%':      { transform: 'translate(-5%, 25%)' },
                    '50%':      { transform: 'translate(-15%, 10%)' },
                    '60%':      { transform: 'translate(15%, 0%)' },
                    '70%':      { transform: 'translate(0%, 15%)' },
                    '80%':      { transform: 'translate(3%, 35%)' },
                    '90%':      { transform: 'translate(-10%, 10%)' },
                },
            },
            transitionTimingFunction: {
                'spring': 'cubic-bezier(0.16, 1, 0.3, 1)',
            },
        },
    },
    plugins: [],
}
